server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
spring:
  application:
    name: zuul


zuul:
  add-host-header: true
  routes:
    test:
      path: /ooo/**
      serviceId: app1